# Generated by Django 4.2.7 on 2024-01-24 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articlesru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('img', models.ImageField(blank=True, upload_to='static/images', verbose_name='Фото')),
                ('anons', models.CharField(max_length=250, verbose_name='Описание')),
                ('full_text_ru', models.TextField(verbose_name='Текст')),
                ('tags', models.TextField(default='', verbose_name='Теги темы')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания')),
                ('isopub', models.BooleanField(default=False, verbose_name='Выложено')),
            ],
        ),
    ]
