# Generated by Django 4.2.7 on 2024-01-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articlesru',
            new_name='News',
        ),
    ]
